# Generated by Django 5.2.4 on 2025-07-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('1', 'Income'), ('2', 'Expense')], max_length=50)),
            ],
        ),
    ]
