# Generated by Django 5.2.4 on 2025-08-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_desc',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
