# Generated by Django 5.2.4 on 2025-08-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_subcategory_subcategory_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_type',
        ),
    ]
