# Generated by Django 5.2.4 on 2025-08-09 06:35

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_transaction_apr_1_a_alter_transaction_apr_1_q_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='year',
            field=models.CharField(choices=[(2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045)], default=webapp.models.current_year, max_length=50),
        ),
    ]
