# Generated by Django 5.2.4 on 2025-08-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_transaction_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
