# Generated by Django 5.2.4 on 2025-08-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_transaction_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
