# Generated by Django 5.2.4 on 2025-08-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_subcategory_subcategory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_type',
        ),
    ]
